---
title: "Welcome to Kim - A data journey"
description: |
  Welcome to my new blog, Kim - A data journey. This blog includes the projects I completed from the Udacity 3 month-program in 1 month. I hope you enjoy reading!
author:
  - name: kim
    url: https://example.com/norajones
    affiliation: Udacity Nanodegree
    #affiliation_url: https://example.com/spacelysprokets
date: 05-22-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

## A short introduction:
If data analyst is your dream, this program is a good starting point to get feeling about what a data analyst does. For sure, it will be a long journey with a lot of effort and experiences accumulated. However, good first steps are always beneficial.

Below is the set of 3 out of 4 projects required by the Udacity Nanodegree program. It starts from the easiest level to the most complicated one. Personally, the A/B testing part is the one I struggled a lot. 

### [Patient Appointment](Prj2_Appointment_2.html).


A person makes a doctor appointment, receives all instructions and do not show. The question is what factors will keep them to be present more regularly. This project tries to find out these things by analyzing the a dataset of **100k** medical appointments in Brazil.


### [A/B Testing for website](3.Analyze_ab_test_results_notebook.html).


A/B tests are very commonly performed by data analysts and data scientists. This project implements an A/B test run by an e-commerce website. The goal is to help the company understand if they should implement the new page, keep the old page, or perhaps run the experiment longer to make their decision.


### [Dog rating using Twitter data](4.wrangle_act.html).


This is a brief analysis of ratings done by WeRateDogs, which is a twitter account that professionally rates dogs. The main parts of this project is data wrangle and cleaning then exlore some insights from the cleaned data.

For users, they like getting good ratings, retweets or favorites from other. For Twitter, knowing which devices users utlizing is also necessary for them to improve their products.


### [FordGoBike data exploration and analysis](5.Exploration_slide_deck.slides.html).


This is the final part which includes data wrangling, cleaning, visualising and producing a slide deck for presenting to clients. In this investigation, I download the data in 7 consequencial months from 9/2019 - 3/2020 of FordGoBike. The dataset can be found and downloaded from https://s3.amazonaws.com/baywheels-data/index.html. The feature description documentation is  available at https://www.lyft.com/bikes/bay-wheels/system-data
    
It includes 1698486 rows of data with 15 features. Half of them are in numerics, and half are in object. I just take a sample of 16984 rows to work with to ensure the data enough large but also not hard to computing.
    
Ford GoBike is the Bay Area's bike share system with 700 bikes and 70 stations and will grow to 7,000 across San Francisco and San Jose. Riders can unlocked the bike from one station and returned to any other station.The bikes are available for use 24 hours/day, 7 days/week, 365 days/year and riders have access to all bikes in the network when they become a member or purchase a pass.

